import { Task } from "./interfaces";

export const taskRows: Task[] = [
  {
    id: 1,
    taskName: "Design Mockup",
    assignee: "Jane Doe",
    dueDate: "2024-01-05",
    issueDate: "2023-12-15",
    hoursSpent: 10,
    project: "Project A",
    difficulty: "medium",
  },
  {
    id: 2,
    taskName: "Code Review",
    assignee: "John Smith",
    dueDate: "2024-01-07",
    issueDate: "2023-12-20",
    hoursSpent: 5,
    project: "Project B",
    difficulty: "hard",
  },
  {
    id: 3,
    taskName: "User Testing",
    assignee: "Alice Johnson",
    dueDate: "2024-01-10",
    issueDate: "2023-12-25",
    hoursSpent: 15,
    project: "Project C",
    difficulty: "easy",
  },
  {
    id: 4,
    taskName: "API Integration",
    assignee: "Bob Brown",
    dueDate: "2024-01-12",
    issueDate: "2023-12-30",
    hoursSpent: 20,
    project: "Project D",
    difficulty: "medium",
  },
  {
    id: 5,
    taskName: "Database Optimization",
    assignee: "Charlie Davis",
    dueDate: "2024-01-15",
    issueDate: "2024-01-01",
    hoursSpent: 25,
    project: "Project E",
    difficulty: "hard",
  },
];
